### ISSUE TITLE
Is this project still alive/active or will continue to be worked on? 

### ISSUE THREAD

**Issue by coreybruce** [AMDmi3/openstrike#20]
I can see this hasn't been worked on or updated in 6/7 years but  I was wondering if development will continue at all as I would love to play this old classic.

**Comment by AMDmi3** [comment]
Well it is as it looks, not actively maintained but not officially cancelled. That is, I don't plan to work on it anytime soon, but pull requests are welcome.

For the note, I've kinda lost interest in it after discovering that it would require a lot more reverse engineering that I'm comfortable with. For instance, I couldn't find terrain tiles in the data, which means they are probably generated in the code somehow. Another problem I couldn't solve is non-obvious offset in object (building) placement.

**Comment by coreybruce** [comment]
That's all good I understand :)
